id = "ctags"
name = "Universal Ctags LSP support"
version = "0.0.1"
schema_version = 1
authors = ["Mateusz Mazur <mateusz.mazur@hey.com>"]
description = "Add Universal Ctags support to the Zed editor"
repository = "https://github.com/mazurel/zed-ctags"

[language_servers.ctags-lsp]
name = "Universal Ctags LSP"
languages = ["C", "C++", "Python"]
